// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "../h/stdafx.h"
#include "../h/agrubberbandpickinfodata.h"

// Dispatch interfaces referenced by this interface
#include "../h/agobjpathcollection.h"


/////////////////////////////////////////////////////////////////////////////
// CAgRubberBandPickInfoData properties

/////////////////////////////////////////////////////////////////////////////
// CAgRubberBandPickInfoData operations

CAgObjPathCollection CAgRubberBandPickInfoData::GetObjPaths()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CAgObjPathCollection(pDispatch);
}
