#if !defined(AFX_AGUIAX2DCNTRL_H__26AF64F0_E901_4FCF_9108_00B11BD6263B__INCLUDED_)
#define AFX_AGUIAX2DCNTRL_H__26AF64F0_E901_4FCF_9108_00B11BD6263B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;
class CAgPickInfoData;
class CAgSTKXApplication;

/////////////////////////////////////////////////////////////////////////////
// CAgUiAx2DCntrl wrapper class

class CAgUiAx2DCntrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAgUiAx2DCntrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7C55F3C4, 0x7629, 0x4FCC, { 0xB9, 0xFE, 0x57, 0x2B, 0x3F, 0x4C, 0xE4, 0x6B } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetRefPicture(LPDISPATCH newValue);
	void SetPicture(LPDISPATCH newValue);
	CPicture GetPicture();
	long GetWinID();
	void SetWinID(long nNewValue);
	void ZoomIn();
	void ZoomOut();
	CAgPickInfoData PickInfo(long x, long y);
	CAgSTKXApplication GetApplication();
	BOOL GetAllowScrollbars();
	void SetAllowScrollbars(BOOL bNewValue);
	BOOL GetNoLogo();
	void SetNoLogo(BOOL bNewValue);
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	void SetVendorID(LPCTSTR lpszNewValue);
	CString GetVendorID();
	long GetMouseMode();
	void SetMouseMode(long nNewValue);
	void CopyFromWinID(long WinID);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGUIAX2DCNTRL_H__26AF64F0_E901_4FCF_9108_00B11BD6263B__INCLUDED_)
